services:
  postgres:
    image: postgres:15-alpine
    container_name: go_backend_postgres
    environment:
      POSTGRES_USER: gunashfarzaliyev
      POSTGRES_PASSWORD: SecurePass2024!Cinema
      POSTGRES_DB: godb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gunashfarzaliyev -d godb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

